version: '3.9'

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge

services:
    cloudcmd:
        image: coderaiser/cloudcmd
        container_name: cloudcmd
        restart: always
        labels:
          - "traefik.enable=true"
          - "traefik.backend=cloudcmd"
          - "traefik.frontend.rule=Host:cloudcmd.${DOMAINNAME}"
          - "traefik.port=8000"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${POOLERINO}:/poolerino
          - ${NICEMEME}:/downloads
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    traefik:
        image: traefik:v1.7.30-alpine
        container_name: traefik
        restart: always
        hostname: traefik
        domainname: ${DOMAINNAME}
        networks:
          - default
          - traefik_proxy
        ports:
          - 80:80
          - 443:443
          - 8080:8080
        labels:
          - "traefik.enable=true"
          - "traefik.backend=traefik"
          - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
          - "traefik.port=8080"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/traefik:/etc/traefik
          - ${CONTAINERDATA}/traefiktmp:/tmp
        environment:
          - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
          - CF_API_KEY=${CLOUDFLARE_API_KEY}

    vpn:
        image: dperson/openvpn-client
        container_name: vpn
        restart: always
        hostname: vpn
        extra_hosts:
          - "qbittorrent.${DOMAINNAME}:${DOCKERHOSTIP}"
          - "sabnzbd.${DOMAINNAME}:${DOCKERHOSTIP}"
          - "sonarr.${DOMAINNAME}:${DOCKERHOSTIP}"
          - "sonarr4k.${DOMAINNAME}:${DOCKERHOSTIP}"
          - "radarr.${DOMAINNAME}:${DOCKERHOSTIP}"
          - "radarr4k.${DOMAINNAME}:${DOCKERHOSTIP}"
          - "bazarr.${DOMAINNAME}:${DOCKERHOSTIP}"
          - "prowlarr.${DOMAINNAME}:${DOCKERHOSTIP}"
        cap_add:
          - NET_ADMIN
        networks:
          - default
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/vpn:/vpn
          - /dev/net:/dev/net:z
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}
        working_dir: "/vpn"
        dns:
          - ${VPNDNS}
        sysctls:
          - net.ipv6.conf.all.disable_ipv6=0
        command: -f ""

    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        restart: always
        depends_on:
          - vpn
        network_mode: "service:vpn"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=qbittorrent"
          - "traefik.frontend.rule=Host:qbittorrent.${DOMAINNAME}"
          - "traefik.port=8091"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/qbittorrent:/config
          - ${NICEMEME}:/downloads
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}
          - WEBUI_PORT=8091

    prowlarr:
        image: ghcr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        restart: always
        depends_on:
          - vpn
        network_mode: "service:vpn"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=prowlarr"
          - "traefik.frontend.rule=Host:prowlarr.${DOMAINNAME}"
          - "traefik.port=9696"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/prowlarr:/config
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    sabnzbd:
        image: linuxserver/sabnzbd
        container_name: sabnzbd
        restart: always
        hostname: sabnzbd
        networks:
          - traefik_proxy
        labels:
          - "traefik.enable=true"
          - "traefik.backend=sabnzbd"
          - "traefik.frontend.rule=Host:sabnzbd.${DOMAINNAME}"
          - "traefik.port=8080"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/sabnzbd:/config
          - ${NICEMEME}:/downloads
          - ${NICEMEME}:/incomplete-downloads
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        restart: always
        depends_on:
          - vpn
        network_mode: "service:vpn"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=sonarr"
          - "traefik.frontend.rule=Host:sonarr.${DOMAINNAME}"
          - "traefik.port=8989"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/sonarr:/config
          - ${NICEMEME}:/downloads
          - ${TV}:/tv
          - ${ANIME}:/anime
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    sonarr4k:
        image: linuxserver/sonarr
        container_name: sonarr4k
        restart: always
        depends_on:
          - vpn
        network_mode: "service:vpn"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=sonarr4k"
          - "traefik.frontend.rule=Host:sonarr4k.${DOMAINNAME}"
          - "traefik.port=8990"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/sonarr4k:/config
          - ${NICEMEME}:/downloads
          - ${TV4K}:/tv4k
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        restart: always
        depends_on:
          - vpn
        network_mode: "service:vpn"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=radarr"
          - "traefik.frontend.rule=Host:radarr.${DOMAINNAME}"
          - "traefik.port=7878"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/radarr:/config
          - ${NICEMEME}:/downloads
          - ${MOVIES}:/movies
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    radarr4k:
        image: linuxserver/radarr
        container_name: radarr4k
        restart: always
        depends_on:
          - vpn
        network_mode: "service:vpn"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=radarr4k"
          - "traefik.frontend.rule=Host:radarr4k.${DOMAINNAME}"
          - "traefik.port=7879"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/radarr4k:/config
          - ${NICEMEME}:/downloads
          - ${MOVIES4K}:/movies4k
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    bazarr:
        image: linuxserver/bazarr
        container_name: bazarr
        restart: always
        depends_on:
          - vpn
        network_mode: "service:vpn"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=bazarr"
          - "traefik.frontend.rule=Host:bazarr.${DOMAINNAME}"
          - "traefik.port=6767"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/bazarr:/config
          - ${MOVIES}:/hehe/Film
          - ${ANIME}:/hehe/Anime
          - ${TV}:/tv
          - ${MOVIES}:/movies
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    overseerr:
        image: sctx/overseerr
        container_name: overseerr
        restart: always
        hostname: overseerr
        networks:
          - traefik_proxy
        labels:
          - "traefik.enable=true"
          - "traefik.backend=overseerr"
          - "traefik.frontend.rule=Host:overseerr.${DOMAINNAME}"
          - "traefik.port=5055"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/overseerr:/app/config
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}
          - LOG_LEVEL=info

    tautulli:
        image: linuxserver/tautulli
        container_name: tautulli
        restart: always
        hostname: tautulli
        networks:
          - traefik_proxy
        labels:
          - "traefik.enable=true"
          - "traefik.backend=tautulli"
          - "traefik.frontend.rule=Host:tautulli.${DOMAINNAME}"
          - "traefik.port=8181"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/tautulli:/config
          - ${CONTAINERDATA}/tautulli:/logs
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        restart: always
        hostname: duplicati
        networks:
          - traefik_proxy
        labels:
          - "traefik.enable=true"
          - "traefik.backend=duplicati"
          - "traefik.frontend.rule=Host:duplicati.${DOMAINNAME}"
          - "traefik.port=8200"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/duplicati:/config
          - ${DUPLICATI}:/backups
          - ${CONTAINERDATA}:/source:ro
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}

    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: always
        hostname: portainer
        labels:
          - "traefik.enable=true"
          - "traefik.backend=portainer"
          - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"
          - "traefik.port=9000"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/portainer:/data
        command: -H unix:///var/run/docker.sock

    gotify:
        image: gotify/server
        container_name: gotify
        restart: always
        hostname: gotify
        labels:
          - "traefik.enable=true"
          - "traefik.backend=gotify"
          - "traefik.frontend.rule=Host:gootify.${DOMAINNAME}"
          - "traefik.port=80"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONTAINERDATA}/gotify:/app/data
        environment:
          - PGID=${PGID}
          - PUID=${PUID}
          - TZ=${TZ}
