version: '3'

services:
    deluge:
        image: linuxserver/deluge
        container_name: deluge
        hostname: deluge
        restart: always
        ports:
            - 8112:8112
            - 58846:58846
            - 55204:55204
            - 55204:55204/udp
        volumes:
            - deluge:/config
            - nicememe:/downloads
            - scripts:/scripts
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        hostname: transmission
        restart: always
        ports:
            - 9091:9091
            - 55206:55206
            - 55206:55206/udp
        volumes:
            - transmission:/config
            - nicememe:/downloads
            - nicememe:/watch
            - scripts:/scripts
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        hostname: jackett
        restart: always
        ports:
            - 9117:9117
        volumes:
            - jackett:/config
            - nicememe:/downloads
            - scripts:/scripts
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    sonarr:
        image: linuxserver/sonarr:preview
        container_name: sonarr
        hostname: sonarr
        restart: always
        ports:
            - 8989:8989
        volumes:
            - sonarr:/config
            - /home/turd/hehe/Serie:/tv
            - /home/turd/hehe/Anime:/anime
            - nicememe:/downloads
            - scripts:/scripts
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        hostname: radarr
        restart: always
        ports:
            - 7878:7878
        volumes:
            - radarr:/config
            - /home/turd/hehe/Film:/hehe/Film
            - /home/turd/hehe/Film:/movies
            - /home/turd/hehe/Asian:/hehe/Asian
            - scripts:/scripts
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    bazarr:
        image: linuxserver/bazarr
        container_name: bazarr
        hostname: bazarr
        restart: always
        ports:
            - 6767:6767
        volumes:
            - bazarr:/config
            - /home/turd/hehe/Film:/movies
            - /home/turd/hehe/Asian:/hehe/Asian
            - /home/turd/hehe/Film:/hehe/Film
            - /home/turd/hehe/Anime:/hehe/Anime
            - /home/turd/hehe/Serie:/tv
            - /home/turd/hehe/Anime:/anime
            - scripts:/scripts
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        hostname: ombi
        restart: always
        ports:
            - 3579:3579
        volumes:
            - ombi:/config
            - scripts:/scripts
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        hostname: duplicati
        restart: always
        ports:
            - 8200:8200
        volumes:
            - duplicati:/config
            - /home/turd/duplicatilocal:/backups
            - /data/config:/source:ro
            - scripts:/scripts
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    influxdb:
        image: influxdb
        container_name: influxdb
        hostname: influxdb
        restart: always
        ports:
            - 8086:8086
        volumes:
            - influxdb:/var/lib/influxdb
            - scripts:/scripts
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        ports:
            - 3000:3000
        volumes:
            - grafana:/var/lib/grafana
            - scripts:/scripts
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
        depends_on:
            - influxdb

    varken:
        image: boerderij/varken
        container_name: varken
        hostname: varken
        restart: always
        volumes:
            - varken:/config
            - scripts:/scripts
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}

    portainer:
        image: portainer/portainer
        container_name: portainer
        hostname: portainer
        restart: always
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer:/data
            - scripts:/scripts
        command: -H unix:///var/run/docker.sock
        
    ouroboros:
        image: pyouroboros/ouroboros
        container_name: ouroboros
        hostname: ouroboros
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    deluge:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/deluge
    transmission:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/transmission
    jackett:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/jackett
    sonarr:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/sonarr
    radarr:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/radarr
    bazarr:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/bazarr
    ombi:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/ombi
    duplicati:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/duplicati
    influxdb:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/influxdb
    grafana:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/grafana
    varken:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/varken
    portainer:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config/portainer
    nicememe:
        driver: local-persist
        driver_opts:
            mountpoint: /home/turd/nicememe
    scripts:
        driver: local-persist
        driver_opts:
            mountpoint: /home/turd/scripts
